### ISSUE TITLE
Whoopi

### ISSUE THREAD

**Issue by olien** [omphteliba/ff_degas#3]
Sobald ich durch klick auf "Degas" klicke erhalte ich ein Woops

https://abc.local/redaxo/index.php?page=ff_degas/image

![image](https://github.com/omphteliba/ff_degas/assets/330516/816aa643-6bca-48e1-b8f9-622807e2aefe)

**Comment by omphteliba** [comment]
Hah! Bei mir auch. Ich schaus mir mal an.

**Comment by omphteliba** [comment]
da hat sich wohl irgendwas im aufruf der seiten geänert. ich habs direkt hier in github gefixt, schau mal obs bei dir das Problem löst.

**Comment by olien** [comment]
Der Fehler ist weg. ich schreib aber n neues issue :;-)
(Sorry für die späte Antwort. hab keine mail von GitHub bekommen..)

**Comment by omphteliba** [comment]
Wunderbar!
